spring:
  application:
    name: chat
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chat?serverTimezone=Asia/Seoul
    username: ghrnwjd
    password: 1234
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
